---
title: "Why Do We Calculate Means and Variances"
---

<div style = "margin-bottom:75px;">

</div>

<div style = "margin-bottom:50px;">

**Observations** Information, including *measurements*, that is collected from organisms of the environment, also known as *data*.

**Data** are used to test *hypotheses*.

In ecology, scientists often to know the **mean**, or average value, of the data collected from different experimental treatments or under different environmental conditions.  

</div>

<div style = "margin-bottom:50px;">

**Example study** 

Scientists collected data on the density of herbivorous insects and the amount of leaf tissue the herbivores consumed.

**Oak tree experiment**

Researchers wanted to compare the mean density of insects on caged trees versus uncaged trees to determine whether birds depressed the number of insects consuming tree leaves.

While comparison of the different means describes the central tendencies of the data,
ecologists often want to know if the data used to generate the mean have high or low variability.

If the mean density of insects on leaves was 10 insects per square meter of leaf surface in both of the following sets of data, which group is more variable?

</div>

<div style = "margin-bottom:50px;">
```{r bio239 line X, echo = TRUE}
groupA <- c(10, 9, 11, 10, 8, 12, 9, 11, 8, 12)

groupB <- c(10, 5, 15, 10, 6, 14, 5, 15, 7, 13)

mean(groupA)

mean(groupB)

var(groupA)

var(groupB)
```
</div>

<div style = "margin-bottom:50px;">

Although both groups have a mean of 10, observations on Group A have less variability than Group B.

Given that each mean is calculated from a set of data that has either a narrow or wide range, 
the variability describes how much the distributions of data overlap with each other. If two groups 
have different means but the distributions of data overlap a great deal, such as the number of insects on 
caged and uncaged trees, then we cannot be confident that the two groups are actually different from each other. 

One way to measure the variability around the mean is to calculate the variance of the mean. 
The **variance of the mean** is a measurement that indicates the spread of data around the mean of a population 
when every member of the population is measured. Data points that are more widely spread around the mean will 
have higher variance. 

</div>

<div style = "margin-bottom:50px;">

Calculate the variance (denoted as $\sigma^2$) in a set of data:

1. Square each observed value (denoted as $\chi$) and calculate the mean of these squared values (where *E* indicates that we are taking the mean of several values):

$E$[$\chi^2$]

2. From this mean, subtract the square of the mean observed value:

$\sigma^2$ = $E$[$\chi^2$] - [$E$($\chi$)]$^2$

In words, $E$[$\chi^2$] is the mean of the squared observed values and [$E$($\chi$)]$^2$ is the square of the mean observed values.

</div>

<div style = "margin-bottom:50px;">

When we calculate the variance of the mean, the calculation is based on the assumption that we have measured every member of the population. In reality, we cannot measure every individual, but we can measure a *sample* of the entire population.

In the oak tree experiment, the researchers did not measure all the insects on all the trees, but instead a sample of 10 groups of oak trees.
When we measure a sample of the population, the variation in the data is called the **sample variance**. The sample variance is very similar to the **variance of the mean**, except we now account for how many samples of the populaton we measured (denoted as $n$). The sample variance (denoted as $s^2$) is calculated as:

$s^2$ = $\frac{n}{n-1} * \sigma^2$

or 

$s^2$ = $\frac{n}{n-1} * E[\chi^2] - [E(\chi)]^2$

</div>
















