---
title: "Calculating Life Table Values"
---

```{r bio239 line 5, include = FALSE, echo = FALSE}
require(tidyverse)
require(knitr)
```

<div style = "margin-bottom:75px;">
</div>

<div style = "margin-bottom:75px;">
Life table data are collected for many different species. For example, a group of researchers spent a decade following a population of grey squirrels 
</div>

<div style = "margin-bottom:50px;">

Gray Squirrel Life Table

```{r table1, echo = FALSE, message = FALSE, warnings = FALSE, results ='asis'}
tabl <- "
|(x) |($n_{x}$)|($l_{x}$)|($b_{x}$)|($l_{x}$) x ($b_{x}$)|($x$) x ($l_{x}$) x ($b_{x}$)|
|:--:|:-------:|:-------:|:-------:|:-------------------:|:---------------------------:|
| 0  | 530     | 1.000 | 0.05      |                     |                             |
| 1  | 134     | 0.253 | 1.28      |                     |                             |
| 2  | 56      | 0.116 | 2.28      |                     |                             |
| 3  | 39      | 0.089 | 2.28      |                     |                             |
| 4  | 23      | 0.058 | 2.28      |                     |                             |
| 5  | 12      | 0.039 | 2.28      |                     |                             |
| 6  | 5       | 0.025 | 2.28      |                     |                             |
| 7  | 2       | 0.022 | 2.28      |                     |                             |
"
cat(tabl)
```
</div>

<div style = "margin-bottom:75px;">

Using data in the table

1. Calculate the net reproductive rate ($R_{0}$)

2. Calculate generation time ($T$)

3. Calculate the intrinsic rate of increase ($\lambda$)

</div>